/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./components/Admin.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    ManageUser: typeof import('./components/ManageUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sale: typeof import('./components/Sale.vue')['default']
    SaleDataForm: typeof import('./components/SaleDataForm.vue')['default']
    SalesDataForm: typeof import('./components/SalesDataForm.vue')['default']
    ThemeToggleButton: typeof import('./components/ThemeToggleButton.vue')['default']
    UserManagement: typeof import('./components/UserManagement.vue')['default']
  }
}
